SRC = actors.c audio.c  board.c    canvas.c   computer.c   field.c   human.c   iface.c   list.c   network.c   sprite.c   theme.c   toolkit.c   Xarchon_Problem.cpp   Xarchon_Interface.cpp   Xarchon_Game.cpp   Xarchon_Genetic.cpp

CC=gcc
CFLAGS=-I. -Ixaw -g -O0

ALL: main

main: toolkit.o xaw/xaw-toolkit.o board.o
